# Generated by Django 5.1.3 on 2024-11-24 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz_nome', models.CharField(max_length=200)),
                ('qtd_linhas_m', models.IntegerField(default=0)),
                ('qtd_colunas_n', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.IntegerField()),
                ('coluna', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitescreen.matriz')),
            ],
        ),
    ]
